### ISSUE TITLE
[IOS] Background Music stops when opening the app

### ISSUE THREAD

**Issue by ishigamii** [react-native-kit/react-native-track-player#502]
# Configuration
package.json
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-track-player": "^1.1.3",
    "react-native-swift": "^1.2.2",
```

react-native info
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

# Problem 
If you are listening to music from anything else on your phone and you start the application. Even if the player is not created yet by calling `TrackPlayer.setupPlayer()` the music gets stopped as soon as the app starts. 
This problem only happened to me on iOS. And after the app is launched we can go back to music play and go back to the app the music won't stop (except when calling the play on the player but that's normal behaviour) ;) 

Did I miss a step of the configuration or is that a bug ? 

I think it is related but when I was launching the app from XCode I saw this logs coming in loop : 
```
xxx[553:35364] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port 擴音 (type: Speaker)
```

**Comment by thessler27** [comment]
#484 fixed that, if you use the `dev` branch and then clean/rebuild, you'll be able to utilize background music until you `play()`

**Comment by ishigamii** [comment]
@thessler27 I will give it a try even though I don't create the player until further in the app so that's still sounds a little different no ? 👍

**Comment by thessler27** [comment]
@ishigamii it does sound slightly different, but this might work. let me know. it all depends on how it initializes

**Comment by ishigamii** [comment]
@thessler27 I just plugged myself on the dev version and sadly it seems that it's has some bugs as I can't compile it right away 
<img width="235" alt="Capture d’écran 2019-03-19 à 13 59 07" src="https://user-images.githubusercontent.com/26909067/54607805-912c9280-4a4f-11e9-80ba-94e57cf1a7f9.png">
Am I missing something ? should I link the lib again ?

**Comment by thessler27** [comment]
clean the app `cmd+k` and rebuild. should fix this

**Comment by ishigamii** [comment]
@thessler27 even after rebooting and cleaning with `cmd+Shift+K` the build still gives these errors

**Comment by thessler27** [comment]
try linking the lib again with `react-native link react-native-track-player` so that it gets the new models

**Comment by ishigamii** [comment]
@thessler27 also did that twice going back to the normal branch but still getting this error with the dev branch 
To go to the dev branch I used : `yarn add react-native-kit/react-native-track-player#dev`

**Comment by thessler27** [comment]
try to uninstall and reinstall the plugin? and confirm that `SessionCategories.swift` is in your xcode project

**Comment by ishigamii** [comment]
@thessler27 you were actually quite right the `SessionCategories.swift` was missing in the project even after removing it and installing it again. I did add it by hand in xcode and now seems to compile gonna give it a try thanks for help and sorry for not noticing it before 👍

**Comment by thessler27** [comment]
That's weird that it's not installing with the package. Glad it compiled

**Comment by ishigamii** [comment]
@thessler27 just gave it a try and sadly It doesn't correct my problem as the sound stop as soon as I launch the app for the first time. If I go back to music and play I don't have any problem afterward as it only stop it when I tap on the play button and that launch the other track. Maybe it's the configuration of the iOS program ? 
When I was using another lib I added this : 
<img width="986" alt="Capture d’écran 2019-03-20 à 10 12 45" src="https://user-images.githubusercontent.com/26909067/54672604-c93be000-4af8-11e9-8a9d-4815cc1c51f6.png">

and also this snippet which was supposed to allow playing in the lock screen maybe that's the problem
```
  NSError *setCategoryErr = nil;
  NSError *activationErr  = nil;
  [[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryPlayback error:&setCategoryErr];
  [[AVAudioSession sharedInstance] setActive:YES error:&activationErr];
```

That must be the faulty piece of code :/ I will give it a try by removing it

**Comment by ishigamii** [comment]
@thessler27 It was indeed that piece of code that was causing the stop when launching the app I will be back to the normal branch it should be working with the `1.1.3` version
So I just tried the `1.1.3` version and it's working well with it
Thanks for your help 👍 Hope to see a `1.1.4` soon ❤️

**Comment by curiousdustin** [comment]
I also had the same issue with the missing `SessionCategories.swift` file, when trying to compile the example. 

Will this be addressed?

**Comment by ishigamii** [comment]
@curiousdustin make a PR for it just adding the file to the project I think it's just missing there that's all 
@thessler27 want me to do it or will you  ? :)

**Comment by curiousdustin** [comment]
I think you should, because I'm not understanding why it is not included when you install and link the react-native-track-player module. The file is there, it just doesn't get included for some reason.

**Comment by thessler27** [comment]
Looks like #500 addresses this
